Re-queue message with response code 426
synduit/rabbitmq-worker pull request #7
Opened 2017-06-19 09:05 UTC by karthikbodu

Re-queue message with response code 426

2017-06-19 12:23 UTC, msound approved these changes

2017-06-19 20:53 UTC, msound requested changes

2017-06-19 20:53 UTC, msound commented on message/message.go
> +	if resp.StatusCode >= 400 && resp.StatusCode <= 499 && resp.StatusCode != 426 {
@karthikbodu Are you sure it is 426? I think it is 429. Please double check.

2017-06-21 05:49 UTC, tkuldeep approved these changes

2017-06-21 05:49 UTC, tkuldeep commented
@msound Changes requested by you has been fixed. so merging it.

2017-06-21 05:50 UTC, merged